// Fetch user by token 
export const FETCH_USER_BY_TOKEN_REQUESTING = 'FETCH_USER_BY_TOKEN_REQUESTING'
export const FETCH_USER_BY_TOKEN_SUCCESS = 'FETCH_USER_BY_TOKEN_SUCCESS'
export const FETCH_USER_BY_TOKEN_ERROR = 'FETCH_USER_BY_TOKEN_ERROR'